# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TwitSplit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwitSplit
  pod 'RxSwift', '~> 4.1'
  pod 'RxCocoa', '~> 4.1'
  target 'TwitSplitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwitSplitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
